// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

// KeeperCompatible.sol imports the functions from both ./KeeperBase.sol and
// ./interfaces/KeeperCompatibleInterface.sol
import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "./InflationFeed.sol";

contract InflationUpkeep is KeeperCompatibleInterface {
    uint public immutable interval;
    uint public lastTimeStamp;
    InflationFeed public inflationOracle;
    

    constructor(uint updateInterval, address _inflationFeedAddress) {
      interval = updateInterval;
      lastTimeStamp = block.timestamp;
      inflationOracle = InflationFeed(_inflationFeedAddress);
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        upkeepNeeded = (block.timestamp - lastTimeStamp) > interval;
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;
            inflationOracle.requestInflationData();
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }
}
